---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: download remi repo rpm
  get_url: 
    url: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm 
    dest: /root/

- name: install remi repo rpm
  yum: 
    name: /root/remi-release-7.rpm 
    state: present
- name: install php
  yum: 
    enablerepo: remi,remi-php56
    name: php-fpm,php-mysql 
    state: latest

- name: Enable and start php
  ansible.builtin.systemd:
    name: php-fpm
    enabled: yes
    state: started

- name: Enable and start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
