stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  script:
    - ansible-lint -p /webserver/deploy_webserver.yaml
    - yamllint /webserver/
  allow_failure: true

deploy:
  stage: deploy
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  script:
    - mkdir -p ~/.ssh
    - echo $SSH_KEY > ~/.ssh/id_rsa
    - chmod -R go= ~/.ssh
    - ansible-playbook -i /webserver/inventory/local/hosts /webserver/deploy_webserver.yaml

