---
- name: Download and unzip wordpress src
  ansible.builtin.unarchive:
    src: https://ru.wordpress.org/latest-ru_RU.zip
    dest: /usr/share/nginx/html/
    remote_src: yes
  tags: 
  - update_wp
  - never

- name: Deploy wordpress config
  template:
    src: "{{ role_path }}/templates/wp-config.php.j2"
    dest: "/usr/share/nginx/html/wordpress/wp-config.php"
    force: true


- name: Deploy wp nginx config
  template:
    src: "{{ role_path }}/templates/wp.conf.j2"
    dest: "/etc/nginx/conf.d/wp.conf"
    force: true


- name: Copy favicon
  ansible.builtin.copy:
    src: "{{ role_path }}/files/favicon.ico"
    dest: "/usr/share/nginx/html/favicon.ico"


- name: Change ownership
  ansible.builtin.file:
    path: "/usr/share/nginx/html/wordpress"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx


- name: And we need to restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

